# Generated by Django 5.2.7 on 2025-11-15 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Викторина',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('назва', models.CharField(max_length=255)),
                ('опис', models.TextField(blank=True, null=True)),
                ('дата_створення', models.DateTimeField(auto_now_add=True)),
                ('створив', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Питання',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('текст', models.TextField()),
                ('порядок', models.IntegerField(default=0)),
                ('вікторина', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='питання', to='quiz_logic.викторина')),
            ],
        ),
        migrations.CreateModel(
            name='Відповідь',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('текст', models.CharField(max_length=255)),
                ('правильна', models.BooleanField(default=False)),
                ('питання', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='відповіді', to='quiz_logic.питання')),
            ],
        ),
        migrations.CreateModel(
            name='Результат',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('бали', models.IntegerField(default=0)),
                ('дата', models.DateTimeField(auto_now_add=True)),
                ('вікторина', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_logic.викторина')),
                ('користувач', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
